version: 1.0.{build}
environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: X86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
install:
- cmd: >-
    'C:\projects\gpx\install.bat'

    'echo End install at: & time /t'
build_script:
- cmd: make
