version: 1.0.{build}
environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
install:
  # running under CI
  - '%APPVEYOR_BUILD_FOLDER%\install.bat'
  - 'echo End install at: & time /t'

build_script:
- cmd: >-
    cd "c:\projects\GPX"
    
    
    make "all"


artifacts:
- path: gpx.exe
  name: GPX
  
